version: '2'
services:
    aldemo-app:
        image: aldemo
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://aldemo-mysql:3306/aldemo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    aldemo-mysql:
        extends:
            file: mysql.yml
            service: aldemo-mysql
